- hosts: all
  tasks:
  
  - name: configure repository for docker community edition
  
    yum_repository:
            baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable" 
            gpgcheck: "no"
            name: "Dock"
            enabled: yes
            state: present
            description: "Docker repo"

  - name: docker ce instllation
    command:
            cmd: "dnf install docker-ce -y --nobest --allowerasing --skip-broken"
             
    become: true
  - name: Install pip
    package:
            name: python3-pip
            state: present
 
  - name: Install docker python package
    pip:
            name: docker
            state: present

  - name: Start docker service
    service:
            name: docker
            state: started

  - name: pull httpd image from docker hub
    docker_image:
            source: pull
            name: httpd
            state: present
  - name: copy files to target node
    copy: 
            src: "/var/www/html/home.html"
            dest: "/root/webpages/"

  - name: Start a httpd container 
    community.general.docker_container:
            name: mycontainer1
            image: httpd
            state: started
            ports:
                    - "8000:80"
            detach: yes
  - name: Copy the file into container
    command:
            cmd: "docker cp /root/webpages/home.html mycontainer1:/usr/local/apache2/htdocs/"
